apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-deployment
  namespace: banking-app-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: services-dep
  template:
    metadata:
      labels:
        app: services-dep
    spec:
      containers:
        - name: services-service
          image: bankingappacr123.azurecr.io/banking-app-services-service:placeholder
          imagePullPolicy: Always

          ports:
            - containerPort: 5003          

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: banking-app-config
                  key: SERVICES_PORT

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: banking-app-secrets
                  key: SERVICES_MONGO_URI
                  
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5003

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5003

            initialDelaySeconds: 10
            periodSeconds: 5       