apiVersion: v1
kind: Service

metadata:
  name: mongodb-auth-service
  namespace: banking-app

spec:
  selector:
    app: mongodb-auth

  ports:
    - port: 27017
      targetPort: 27017

  type: ClusterIP