apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: banking-app-dev

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: managed-csi

  resources:
    requests:
      storage: 1Gi

  volumeName: mongodb-pv