apiVersion: v1
kind: Secret
metadata: 
  name: mongo-secret
  namespace: banking-app-dev

type: Opaque
stringData:
  mongo-root-username: process.env.MONGO_INITDB_ROOT_USERNAME
  mongo-root-password: process.env.MONGO_INITDB_ROOT_PASSWORD 