services:

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  auth-service:
    image: bankingappacr123.azurecr.io/banking-app-auth-service:v1.0.${BUILD_NUMBER}
    build:
      context: ./backend/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      - mongodb
    restart: unless-stopped

  gateway:
    image: bankingappacr123.azurecr.io/banking-app-api-gateway:v1.0.${BUILD_NUMBER}
    build:
      context: ./backend/gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./backend/gateway/.env
    depends_on:
      - auth-service
      - offers-service
      - services-service
    restart: unless-stopped

  offers-service:
    image: bankingappacr123.azurecr.io/banking-app-offers-service:v1.0.${BUILD_NUMBER}
    build:
      context: ./backend/offers-service
    container_name: offers-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/offers-service/.env
    depends_on:
      - mongodb      
    restart: unless-stopped

  services-service:
    image: bankingappacr123.azurecr.io/banking-app-services-service:v1.0.${BUILD_NUMBER}
    build:
      context: ./backend/services-service
    container_name: services-service
    ports:
      - "5003:5003"
    env_file:
      - ./backend/services-service/.env

    depends_on:
      - mongodb      
    restart: unless-stopped

  frontend:
    image: bankingappacr123.azurecr.io/banking-app-frontend:v1.0.${BUILD_NUMBER}
    build:
      context: ./frontend
    container_name: banking-ui
    ports:
      - "3000:8080"
    depends_on:
      - gateway
    restart: unless-stopped 

volumes:
  mongodb_data:    