services:

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512m
    restart: unless-stopped

  auth-service:
    image: bankingappacr123.azurecr.io/banking-app-auth-service:${IMAGE_TAG:-local}
    build:
      context: ./backend/auth-service
    container_name: auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      mongodb: 
        condition: service_healthy
        
    restart: unless-stopped

  gateway:
    image: bankingappacr123.azurecr.io/banking-app-gateway:${IMAGE_TAG:-local}
    build:
      context: ./backend/gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    env_file:
      - ./backend/gateway/.env
    depends_on:
      - auth-service
      - offers-service
      - services-service
    restart: unless-stopped

  offers-service:
    image: bankingappacr123.azurecr.io/banking-app-offers-service:${IMAGE_TAG:-local}
    build:
      context: ./backend/offers-service
    container_name: offers-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/offers-service/.env
    depends_on:
      - mongodb      
    restart: unless-stopped

  services-service:
    image: bankingappacr123.azurecr.io/banking-app-services-service:${IMAGE_TAG:-local}
    build:
      context: ./backend/services-service
    container_name: services-service
    ports:
      - "5003:5003"
    env_file:
      - ./backend/services-service/.env

    depends_on:
      - mongodb      
    restart: unless-stopped

  frontend:
    image: bankingappacr123.azurecr.io/banking-app-frontend:${IMAGE_TAG:-local}
    build:
      context: ./frontend
    container_name: banking-ui
    ports:
      - "3000:8080"
    depends_on:
      - gateway
    restart: unless-stopped 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000" # Web UI port
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  mongodb_data:    