apiVersion: apps/v1
kind: Deployment

metadata:
  name: offers-deployment
  namespace: banking-app-dev

spec:
  replicas: 2

  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: offers-service

  template:
    metadata:
      labels:
        app: offers-service

    spec:
      containers:
        - name: offers-service

          image: bankingappacr123.azurecr.io/banking-app-offers-service:placeholder

          imagePullPolicy: Always

          ports:
            - containerPort: 5001

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: banking-app-config
                  key: OFFERS_PORT

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: banking-app-secrets
                  key: OFFERS_MONGO_URI

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5002

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5002

            initialDelaySeconds: 10
            periodSeconds: 5