apiVersion: v1
kind: Service

metadata:
  name: offers-service
  namespace: banking-app-dev

spec:
  selector:
    app: offers-service

  ports:
    - port: 5002
      targetPort: 5002

  type: ClusterIP