apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-deployment
  namespace: banking-app-dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auth-deployment

  template:
    metadata:
      labels:
        app: auth-deployment

    spec:
      containers:
        - name: auth-service

          image: bankingappacr123.azurecr.io/banking-app-auth-service:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5001

          env:
            - name: PORT
              valueFrom:
               configMapKeyRef:
                 name: banking-app-config
                 key: AUTH_PORT

            
            - name: AUTH_SERVICE_URL  
              valueFrom:
                configMapKeyRef:
                  name: banking-app-config
                  key: AUTH_SERVICE_URL

            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: banking-app-config
                  key: CLIENT_URL

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: banking-app-secrets
                  key: AUTH_MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: banking-app-secrets
                  key: AUTH_JWT_SECRET

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5001

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5001

            initialDelaySeconds: 10
            periodSeconds: 5