apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: banking-app-dev

spec:
  selector:
    app: auth-deployment

  ports:
    - port: 5001
      targetPort: 5001

  type: ClusterIP