apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: banking-app-dev
spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
        - name: frontend
          image: bankingappacr123.azurecr.io/banking-app-frontend:placeholder
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:  
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"
    
