apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-app-dev
type: Opaque
stringData:
  AUTH_MONGO_URI: "mongodb://mongodb-service:27017/bank_auth_db"
  OFFERS_MONGO_URI: "mongodb://mongodb-service:27017/bank_offers_db"
  SERVICES_MONGO_URI: "mongodb://mongodb-service:27017/bank_services_db"
  AUTH_JWT_SECRET: "your_jwt_secret_here"