apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: {{ .Values.namespace}} # Keep it inside your application namespace
  labels:
    release: prometheus # MATCHES YOUR HELM DEPLOYMENT
spec:
  selector:
    matchLabels:
      app: auth-service # Matches the label defined on your Kubernetes Service
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace}} # Tells Prometheus to look outside its own namespace
  endpoints:
    - port: auth-service # Matches the name of the port in your Kubernetes Service
      interval: 15s # How frequently Prometheus scrapes metrics
      path: /metrics/auth # The endpoint path we exposed in Step 1