apiVersion: v1
kind: Service

metadata:
  name: offers-service
  namespace: {{ .Values.namespace }}

  labels:
    app: offers-service

spec:
  selector:
    app: offers-service

  ports:
    - name: offers-service
      port: {{ .Values.offersService.service.port }}
      targetPort: {{ .Values.offersService.service.targetPort }}

  type: {{ .Values.offersService.service.type }}