{{- if .Values.secrets.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: banking-app-secrets
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  AUTH_MONGO_URI: {{ .Values.secrets.authMongoUri | quote }}
  OFFERS_MONGO_URI: {{ .Values.secrets.offersMongoUri | quote }}
  SERVICES_MONGO_URI: {{ .Values.secrets.servicesMongoUri | quote }}
  AUTH_JWT_SECRET: {{ .Values.secrets.authJwtSecret | quote }}

{{- end }}