{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: services-service-monitor
  namespace: {{ .Values.namespace }} # Keep it inside your application namespace
  labels:
    release: prometheus # MATCHES YOUR HELM DEPLOYMENT
spec:
  selector:
    matchLabels:
      app: services-service # Matches the label defined on your Kubernetes Service
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }} # Tells Prometheus to look outside its own namespace
  endpoints:
    - port: services-service # Matches the name of the port in your Kubernetes Service
      interval: 15s # How frequently Prometheus scrapes metrics
      path: /metrics/services-service # The endpoint path we exposed in Step 1
{{- end }}